---
title: "Summary of REHO_startpack"
format:
  html:
    code-fold: true
jupyter: python3
---
**REHO -- Renewable Energy Hub Optimizer**

**The purpose of reading is to clarify what REHO is doing and to be familiar with it**

# On the role of districts as renewable energy hubs 
-- by *Luise MIDDELHAUVE*, Présentée le 8 avril 2022

**renewable energy penetration**: Penetration refers to the percentage of electricity generated by a particular resource. 

**Round-trip efficiency (RTE)** is the ratio of the energy output to the energy input of an ESS over a complete charge-discharge cycle

**Energy reference area** is the sum of all above and below ground gross floor areas for whose use heating or air conditioning is necessary.

**Keywords**: *District energy system, Multi-objective optimization, Photovoltaics, Renewable energy integration, Interconnection of energy carriers*

# Introduction
Volatile power generation caused by the fluctuation of solar irradiation --> challenges the capacity of the electrical power grid --> except for maximizing the electricity generated from the sun, the interaction between grids and building energy system should be reduced by maximizeing the self-consumption while decreasing the grid's energy demand; more energy carriers should be considered.

## What are renewable energy hubs?

### The definition
According to Geigl et al., an energy hub is a unit where multiple energy carries can be converted, conditioned, and stored.

"define an energy hub as a place where the production, consumption, storage, and conversion of multiple energy carriers happens."

### classification
according to sectors: industrial or residential

according to scales: macro or micro

## Contributions and novelty
 - scale effect
 - interactions between decentralized energy systems are highlighted in bpth versions of the design strategy of the district energy system and distributed loads are not aggregated.

# Chapter I: Renewable energy hubs at the building scale
 
*How are renewable energy hubs defined at the building scale?* 
 
*What performance indicators should be used to describe renewable energy hubs?*

Modeling Framework:

MILP + MOO + PCA + k-medoids clustering

Highlight the importance of:

 - setting appropriate system boundaries
 - using at least hourly resolution
 - constructional footprint to characterize renewable energy hubs

## Method

**BES**: Building Energy System

**MILP** is used where types and sizes of the different components of the BES are considered as optimization variables.

A selection of conflicting **KPIs** are collected to assist the decision making; **MOO** is performed with ecological, economical, technical and security indicators as objective.

To conduct computational MOO, data reduction techniques are used in the final step. (**PCA**)

### Energy system

The main problem sets are: the set of of buildings B, the set K of all different temperature levels of the heating system, the set of available conversion and storage units U; the different days of the year are represented by periods in the set P, to which hourly timesteps are allocated and contained in set T.

#### Sizing constraints
The main equation for sizing and scheduling problem units are described by
$$
\mathbf{y_{b,u}} * F_{u}^{min} \leq \mathbf{f_{b,u}} \leq \mathbf{y_{b,u}} * F_{u}^{max}
$$

$$
\mathbf{f_{b,u,p,t}} \leq \mathbf{f_{b,u}}
$$

$$
\mathbf{y_{b,u,p,t}} \leq \mathbf{y_{b,u}}
$$

$$
\forall b \in B, \forall u \in U, \forall p \in P, \forall t \in T
$$

f means the unit size; $F_{max}$ and $F_{unit}$ refer to the upper bound and lower bound of the unit installations; y is a binary variable which expresses whether to purchase the unit or not.

#### Energy balances

$$
\dot{E}^{gr, +}_{b,q,t} + \Sigma
$$